language: go

go:
  - 1.15.2

services:
  - docker

script:
  - test -z "$(gofmt -l -d ./)"
  - mkdir coverage
  - docker build . -t test
  - docker run -v "$(pwd)/coverage/":/go/src/app/coverage test

after_success:
  - mv coverage/coverage.txt coverage.txt
  - bash <(curl -s https://codecov.io/bash)
