apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: mart-ingress
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
    rules:
        - host: mart-route
          http:
              paths:
                  - path: /compiler
                    pathType: Prefix
                    backend:
                        service:
                            name: mart-compiler
                            port:
                                number: 8081
                  - path: /executor
                    pathType: Prefix
                    backend:
                        service:
                            name: mart-executor
                            port:
                                number: 8082
                  - path: /verdict
                    pathType: Prefix
                    backend:
                        service:
                            name: mart-verdict
                            port:
                                number: 8083
