apiVersion: v1
kind: Service
metadata:
  name: orchestrator
spec:
  selector:
    app: orchestrator
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: orm
spec:
  selector:
    app: orm
  ports:
  - port: 8084
    targetPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: mart-compiler
spec:
  selector:
    name: mart
  ports:
  - port: 8081
    targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mart-executor
spec:
  selector:
    name: mart
  ports:
  - port: 8082
    targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: mart-verdict
spec:
  selector:
    name: mart
  ports:
  - port: 8083
    targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    targetPort: 5672
    name: "common-port"
  - port: 15672
    targetPort: 15672
    name: "admin-port"